name = "SignatureTensors"
uuid = "5c9b64c6-6bff-409c-98cc-3e0c4aaf8bc2"
version = "0.1.0"
authors = ["Gabriel Riffo <riffo@tu-berlin.de>", "Leonard Schmitz <lschmitz@math.tu-berlin>"]

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Combinatorics = "1.1.0"
Test = "1.11.0"